### ISSUE TITLE
滑块验证获取图片返回404

### ISSUE THREAD

**Issue by Kylinking** [Farmer-chong/new-school-sdk#30]
如题

**Comment by Farmer-chong** [comment]
> 如题

初步估计是因为贵校的URL与我校不一致，可以尝试自己导入endpoint来修改默认的endpoint，相关demo: https://github.com/Farmer-chong/new-school-sdk/blob/master/examples/config.py

其中第18行为滑块验证码

后续还有问题最好可以提供一下测试地址

**Comment by Kylinking** [comment]
URL肯定要修改的，现在问题已经解决了，需要根据不同学校配置不同的请求头字段，否则会直接返404。谢谢。

**Comment by Farmer-chong** [comment]
目前版本的解决方法可以在具体请求函数的时候传入header参数来解决哟, 比如这样:
```python3
# 实例化用户
user:UserClient = Gdust.user_login("account", "password")

header = {
    "field": "context"
}

# 获取课表
course = user.get_schedule(year=2021, term=1, header=header)
```

**Comment by FarmerChillax** [comment]
> 目前版本的解决方法可以在具体请求函数的时候传入header参数来解决哟, 比如这样:
> 
> ```python
> # 实例化用户
> user:UserClient = Gdust.user_login("account", "password")
> 
> header = {
>     "field": "context"
> }
> 
> # 获取课表
> course = user.get_schedule(year=2021, term=1, header=header)
> ```
> 
> 为了优雅的使用，建议目前版本你可以在后端封装一下调用。学校总体配置`header`将会在下一个版本提供支持~

现阶段快速解决方法：@Magicalboys
